name: Scrape
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  scrape:
    name: Scrape
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - name: Install pipenv
        run: pipx install pipenv

      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: 'pipenv'

      - id: make
        name: Run scrape command
        run: |
          pipenv run python setup.py install
          pipenv run nasawildfires modis --indent=2 > data/modis.json
          pipenv run nasawildfires viirs-suomi --indent=2 > data/viirs-suomi.json
          pipenv run nasawildfires viirs-noaa --indent=2 > data/viirs-noaa.json
        env:
          AIRNOW_KEYS: ${{ secrets.AIRNOW_KEYS }}
        shell: bash

      - id: commit
        name: Commit results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions@github.com"
          git config pull.rebase false
          git status
          git pull origin $GITHUB_REF
          git add ./
          git commit -m "Scrape" && git push || true
        shell: bash
